name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: npm install
    - name: Build project
      run: |
        export PATH="$(npm bin):$PATH"
        ng build --prod
