name: CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: install angular cli
      run: npm install @angular/cli
    - name: install dependencies
      run: npm install
    - name: Build project
      run: ng build --prod
